name: flake8-linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install flake8 pycodestyle
      - name: Check syntax
        run: flake8 $(git diff --name-status) --count --statistics --show-source --exit-zero
      - name: Check syntax 1
        run: flake8 manage.py --count --statistics --show-source --exit-zero
      - name: Check git files
        run: | 
          #git diff --name-status
          git --version
